# Generated by Django 6.1 on 2026-08-26 23:38

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('tos_accepted', models.BooleanField(default=False)),
                ('tos_accepted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tos_version', models.IntegerField(default=accounts.models.current_tos_version)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Männlich'), ('female', 'Weiblich')], max_length=6, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('target_calories', models.IntegerField(blank=True, null=True)),
                ('target_fat', models.IntegerField(blank=True, null=True)),
                ('target_protein', models.IntegerField(blank=True, null=True)),
                ('target_carbs', models.IntegerField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, choices=[('diet', 'Abnehmen'), ('maintain', 'Gewicht halten'), ('gain', 'Zunehmen')], max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('data_consent', models.BooleanField(default=False)),
                ('data_consent_date_granted', models.DateTimeField(blank=True, null=True)),
                ('data_consent_date_revoked', models.DateTimeField(blank=True, null=True)),
                ('data_consent_version', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
