import type { RecipeDetail, RecipeListItem } from './recipes.types'

export const recipeDetails: RecipeDetail[] = [
  {
    id: 1,
    slug: '1-chia-pudding-mit-beeren',
    name: 'Chia-Pudding mit Beeren',
    image: null,
    description:
      'Am Abend angerührt, am Morgen fertig. Die Beeren kommen erst kurz vor dem Essen dazu, damit sie nicht durchweichen.',
    servings: 2,
    durationMinutes: 10,
    kcalPerServing: 230,
    proteinPerServing: 8,
    carbsPerServing: 22,
    fatPerServing: 12,
    diets: ['Vegan', 'Vegetarisch'],
    intolerances: ['Glutenfrei', 'Laktosefrei'],
    mealTypes: ['Frühstück', 'Snack'],
    equipment: ['Ohne Kochen'],
    attributes: ['Meal Prep', 'Wenig Zutaten'],
    ingredients: [
      { ingredient: 'Chiasamen', amount: 50, unit: 'g' },
      { ingredient: 'Mandeldrink', amount: 300, unit: 'ml' },
      { ingredient: 'Ahornsirup', amount: 1, unit: 'EL' },
      { ingredient: 'Gemischte Beeren', amount: 150, unit: 'g' },
    ],
    cookingSteps: [
      { step: 1, text: 'Chiasamen, Mandeldrink und Ahornsirup in einer Schüssel verrühren.' },
      {
        step: 2,
        text: 'Fünf Minuten warten und noch einmal gründlich umrühren, damit sich keine Klümpchen bilden.',
      },
      {
        step: 3,
        text: 'Abgedeckt mindestens vier Stunden oder über Nacht in den Kühlschrank stellen.',
      },
      { step: 4, text: 'Auf zwei Gläser verteilen und die Beeren darauf geben.' },
    ],
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 2,
    slug: '2-beeren-bananen-smoothie',
    name: 'Beeren-Bananen-Smoothie',
    image: null,
    description:
      'Tiefgekühlte Beeren machen den Smoothie kalt und dickflüssig, ohne dass Eis nötig ist.',
    servings: 1,
    durationMinutes: 5,
    kcalPerServing: 170,
    proteinPerServing: 4,
    carbsPerServing: 33,
    fatPerServing: 3,
    diets: ['Vegan', 'Vegetarisch'],
    intolerances: ['Glutenfrei', 'Laktosefrei'],
    mealTypes: ['Frühstück', 'Snack'],
    equipment: ['Mixer'],
    attributes: ['Kalorienarm', 'Wenig Zutaten'],
    ingredients: [
      { ingredient: 'Tiefgekühlte Beeren', amount: 150, unit: 'g' },
      { ingredient: 'Banane', amount: 1, unit: 'Stück' },
      { ingredient: 'Mandeldrink', amount: 200, unit: 'ml' },
    ],
    cookingSteps: [
      { step: 1, text: 'Banane schälen und in Stücke brechen.' },
      { step: 2, text: 'Mit Beeren und Mandeldrink in den Mixer geben.' },
      {
        step: 3,
        text: 'Etwa eine Minute auf höchster Stufe mixen, bis keine Stücke mehr zu sehen sind.',
      },
    ],
    createdAt: '2026-09-02T10:00:00Z',
  },
  {
    id: 3,
    slug: '3-joghurt-bowl-mit-walnuessen',
    name: 'Joghurt-Bowl mit Walnüssen',
    image: null,
    description: 'Griechischer Joghurt liefert viel Eiweiß, die Walnüsse sorgen für Biss.',
    servings: 1,
    durationMinutes: 5,
    kcalPerServing: 310,
    proteinPerServing: 22,
    carbsPerServing: 20,
    fatPerServing: 15,
    diets: ['Vegetarisch'],
    intolerances: ['Glutenfrei'],
    mealTypes: ['Frühstück', 'Snack'],
    equipment: ['Ohne Kochen'],
    attributes: ['Proteinreich', 'Wenig Zutaten'],
    ingredients: [
      { ingredient: 'Griechischer Joghurt', amount: 250, unit: 'g' },
      { ingredient: 'Gemischte Beeren', amount: 100, unit: 'g' },
      { ingredient: 'Walnusskerne', amount: 15, unit: 'g' },
      { ingredient: 'Honig', amount: 1, unit: 'TL' },
    ],
    cookingSteps: [
      { step: 1, text: 'Joghurt in eine Schale geben und glatt streichen.' },
      { step: 2, text: 'Walnüsse grob hacken.' },
      { step: 3, text: 'Beeren und Walnüsse auf den Joghurt geben und mit Honig beträufeln.' },
    ],
    createdAt: '2026-09-03T10:00:00Z',
  },
  {
    id: 4,
    slug: '4-ofen-nudeln-mit-feta-und-kirschtomaten',
    name: 'Ofen-Nudeln mit Feta und Kirschtomaten',
    image: null,
    description:
      'Feta und Tomaten garen zusammen im Ofen und ergeben die Sauce, ohne dass ein Topf dafür nötig ist.',
    servings: 4,
    durationMinutes: 40,
    kcalPerServing: 590,
    proteinPerServing: 22,
    carbsPerServing: 70,
    fatPerServing: 24,
    diets: ['Vegetarisch'],
    intolerances: [],
    mealTypes: ['Mittagessen', 'Abendessen'],
    equipment: ['Herd', 'Backofen'],
    attributes: ['Meal Prep'],
    ingredients: [
      { ingredient: 'Kirschtomaten', amount: 500, unit: 'g' },
      { ingredient: 'Feta', amount: 200, unit: 'g' },
      { ingredient: 'Olivenöl', amount: 3, unit: 'EL' },
      { ingredient: 'Knoblauch', amount: 2, unit: 'Zehe' },
      { ingredient: 'Oregano, getrocknet', amount: 1, unit: 'TL' },
      { ingredient: 'Kurze Nudeln', amount: 400, unit: 'g' },
      { ingredient: 'Basilikum', amount: 1, unit: 'Bund' },
      { ingredient: 'Salz', amount: 1, unit: 'Prise' },
    ],
    cookingSteps: [
      { step: 1, text: 'Backofen auf 200 Grad Ober- und Unterhitze vorheizen.' },
      {
        step: 2,
        text: 'Tomaten in eine Auflaufform geben, den Feta als Block in die Mitte legen.',
      },
      {
        step: 3,
        text: 'Knoblauch pressen und mit Olivenöl, Oregano und Salz über Tomaten und Feta verteilen.',
      },
      { step: 4, text: 'Etwa 30 Minuten backen, bis die Tomaten aufplatzen.' },
      { step: 5, text: 'In der Zwischenzeit die Nudeln nach Packungsangabe kochen und abgießen.' },
      {
        step: 6,
        text: 'Feta und Tomaten in der Form zerdrücken, Nudeln unterheben und mit Basilikum bestreuen.',
      },
    ],
    createdAt: '2026-09-04T10:00:00Z',
  },
  {
    id: 5,
    slug: '5-rote-linsensuppe',
    name: 'Rote Linsensuppe',
    image: null,
    description:
      'Rote Linsen zerfallen beim Kochen und machen die Suppe ohne Sahne cremig. Hält sich drei Tage im Kühlschrank.',
    servings: 4,
    durationMinutes: 45,
    kcalPerServing: 330,
    proteinPerServing: 19,
    carbsPerServing: 44,
    fatPerServing: 8,
    diets: ['Vegan', 'Vegetarisch'],
    intolerances: ['Glutenfrei', 'Laktosefrei'],
    mealTypes: ['Mittagessen', 'Abendessen'],
    equipment: ['Herd'],
    attributes: ['Proteinreich', 'Meal Prep'],
    ingredients: [
      { ingredient: 'Rote Linsen', amount: 300, unit: 'g' },
      { ingredient: 'Zwiebel', amount: 1, unit: 'Stück' },
      { ingredient: 'Karotten', amount: 2, unit: 'Stück' },
      { ingredient: 'Knoblauch', amount: 2, unit: 'Zehe' },
      { ingredient: 'Olivenöl', amount: 2, unit: 'EL' },
      { ingredient: 'Tomaten, gehackt', amount: 1, unit: 'Dose' },
      { ingredient: 'Gemüsebrühe', amount: 1.2, unit: 'l' },
      { ingredient: 'Kreuzkümmel, gemahlen', amount: 1, unit: 'TL' },
      { ingredient: 'Zitrone', amount: 0.5, unit: 'Stück' },
    ],
    cookingSteps: [
      { step: 1, text: 'Zwiebel, Karotten und Knoblauch schälen und fein würfeln.' },
      {
        step: 2,
        text: 'Olivenöl in einem großen Topf erhitzen und das Gemüse darin fünf Minuten anschwitzen.',
      },
      { step: 3, text: 'Kreuzkümmel kurz mitrösten, dann Linsen, Tomaten und Brühe dazugeben.' },
      { step: 4, text: 'Zugedeckt etwa 25 Minuten köcheln lassen, bis die Linsen zerfallen.' },
      {
        step: 5,
        text: 'Mit einem Pürierstab grob pürieren und mit Zitronensaft und Salz abschmecken.',
      },
    ],
    createdAt: '2026-09-05T10:00:00Z',
  },
  {
    id: 6,
    slug: '6-gemuese-curry-mit-kokosmilch',
    name: 'Gemüse-Curry mit Kokosmilch',
    image: null,
    description: 'Ein Topf, gut vorzubereiten. Das Gemüse lässt sich nach Saison tauschen.',
    servings: 4,
    durationMinutes: 25,
    kcalPerServing: 390,
    proteinPerServing: 10,
    carbsPerServing: 48,
    fatPerServing: 18,
    diets: ['Vegan', 'Vegetarisch'],
    intolerances: ['Glutenfrei', 'Laktosefrei'],
    mealTypes: ['Mittagessen', 'Abendessen'],
    equipment: ['Herd'],
    attributes: ['Meal Prep', 'Unter 30 Min'],
    ingredients: [
      { ingredient: 'Basmatireis', amount: 250, unit: 'g' },
      { ingredient: 'Süßkartoffel', amount: 1, unit: 'Stück' },
      { ingredient: 'Paprika, rot', amount: 1, unit: 'Stück' },
      { ingredient: 'Brokkoli', amount: 300, unit: 'g' },
      { ingredient: 'Rote Currypaste', amount: 2, unit: 'EL' },
      { ingredient: 'Kokosmilch', amount: 1, unit: 'Dose' },
      { ingredient: 'Kokosöl', amount: 1, unit: 'EL' },
      { ingredient: 'Limette', amount: 1, unit: 'Stück' },
    ],
    cookingSteps: [
      { step: 1, text: 'Reis nach Packungsangabe kochen.' },
      {
        step: 2,
        text: 'Süßkartoffel schälen und würfeln, Paprika in Streifen schneiden, Brokkoli in Röschen teilen.',
      },
      { step: 3, text: 'Kokosöl im Topf erhitzen, Currypaste darin eine Minute anrösten.' },
      {
        step: 4,
        text: 'Süßkartoffel dazugeben, mit Kokosmilch ablöschen und zehn Minuten köcheln lassen.',
      },
      { step: 5, text: 'Paprika und Brokkoli hinzufügen und weitere fünf Minuten garen.' },
      { step: 6, text: 'Mit Limettensaft abschmecken und mit dem Reis servieren.' },
    ],
    createdAt: '2026-09-06T10:00:00Z',
  },
  {
    id: 7,
    slug: '7-lachs-mit-zucchini-aus-der-pfanne',
    name: 'Lachs mit Zucchini aus der Pfanne',
    image: null,
    description: 'Der Lachs wird nur auf der Hautseite gebraten und bleibt innen saftig.',
    servings: 2,
    durationMinutes: 25,
    kcalPerServing: 400,
    proteinPerServing: 36,
    carbsPerServing: 8,
    fatPerServing: 24,
    diets: ['Pescetarisch'],
    intolerances: ['Glutenfrei', 'Laktosefrei'],
    mealTypes: ['Abendessen'],
    equipment: ['Herd'],
    attributes: ['Proteinreich', 'Unter 30 Min'],
    ingredients: [
      { ingredient: 'Lachsfilet mit Haut', amount: 2, unit: 'Stück' },
      { ingredient: 'Zucchini', amount: 2, unit: 'Stück' },
      { ingredient: 'Kirschtomaten', amount: 200, unit: 'g' },
      { ingredient: 'Olivenöl', amount: 2, unit: 'EL' },
      { ingredient: 'Knoblauch', amount: 1, unit: 'Zehe' },
      { ingredient: 'Zitrone', amount: 0.5, unit: 'Stück' },
      { ingredient: 'Salz', amount: 1, unit: 'Prise' },
    ],
    cookingSteps: [
      { step: 1, text: 'Lachs trocken tupfen und salzen, Zucchini in Halbmonde schneiden.' },
      {
        step: 2,
        text: 'Einen Esslöffel Öl in der Pfanne stark erhitzen und den Lachs auf der Hautseite etwa fünf Minuten braten.',
      },
      {
        step: 3,
        text: 'Wenden, die Pfanne vom Herd nehmen und den Lachs in der Resthitze zwei Minuten ziehen lassen.',
      },
      {
        step: 4,
        text: 'Lachs herausnehmen, restliches Öl in die Pfanne geben und Zucchini, Tomaten und Knoblauch fünf Minuten braten.',
      },
      { step: 5, text: 'Gemüse mit Zitronensaft abschmecken und mit dem Lachs anrichten.' },
    ],
    createdAt: '2026-09-07T10:00:00Z',
  },
  {
    id: 8,
    slug: '8-thunfisch-bowl-mit-avocado',
    name: 'Thunfisch-Bowl mit Avocado',
    image: null,
    description: 'Reis vom Vortag reicht völlig. Ohne Sojasauce bleibt die Bowl glutenfrei.',
    servings: 1,
    durationMinutes: 10,
    kcalPerServing: 430,
    proteinPerServing: 30,
    carbsPerServing: 46,
    fatPerServing: 14,
    diets: ['Pescetarisch'],
    intolerances: ['Glutenfrei', 'Laktosefrei'],
    mealTypes: ['Mittagessen', 'Snack'],
    equipment: ['Ohne Kochen'],
    attributes: ['Proteinreich', 'Wenig Zutaten'],
    ingredients: [
      { ingredient: 'Gekochter Reis', amount: 180, unit: 'g' },
      { ingredient: 'Thunfisch im eigenen Saft', amount: 1, unit: 'Dose' },
      { ingredient: 'Avocado', amount: 0.5, unit: 'Stück' },
      { ingredient: 'Salatgurke', amount: 0.5, unit: 'Stück' },
      { ingredient: 'Limette', amount: 0.5, unit: 'Stück' },
    ],
    cookingSteps: [
      { step: 1, text: 'Reis in eine Schale geben.' },
      { step: 2, text: 'Thunfisch abtropfen lassen und auf den Reis setzen.' },
      { step: 3, text: 'Avocado und Gurke in Scheiben schneiden und daneben anrichten.' },
      { step: 4, text: 'Mit Limettensaft beträufeln.' },
    ],
    createdAt: '2026-09-08T10:00:00Z',
  },
  {
    id: 9,
    slug: '9-haehnchen-reis-pfanne-mit-paprika',
    name: 'Hähnchen-Reis-Pfanne mit Paprika',
    image: null,
    description: 'Alles in einer Pfanne. Portionsweise eingefroren hält sie einen Monat.',
    servings: 4,
    durationMinutes: 35,
    kcalPerServing: 500,
    proteinPerServing: 34,
    carbsPerServing: 55,
    fatPerServing: 14,
    diets: [],
    intolerances: ['Glutenfrei', 'Laktosefrei'],
    mealTypes: ['Mittagessen', 'Abendessen'],
    equipment: ['Herd'],
    attributes: ['Proteinreich', 'Meal Prep'],
    ingredients: [
      { ingredient: 'Hähnchenbrust', amount: 500, unit: 'g' },
      { ingredient: 'Langkornreis', amount: 250, unit: 'g' },
      { ingredient: 'Paprika, rot', amount: 2, unit: 'Stück' },
      { ingredient: 'Zwiebel', amount: 1, unit: 'Stück' },
      { ingredient: 'Rapsöl', amount: 2, unit: 'EL' },
      { ingredient: 'Paprikapulver, edelsüß', amount: 2, unit: 'TL' },
      { ingredient: 'Hühnerbrühe', amount: 600, unit: 'ml' },
      { ingredient: 'Frühlingszwiebeln', amount: 1, unit: 'Bund' },
    ],
    cookingSteps: [
      { step: 1, text: 'Hähnchen in mundgerechte Stücke schneiden, Paprika und Zwiebel würfeln.' },
      {
        step: 2,
        text: 'Öl in einer großen Pfanne erhitzen und das Hähnchen rundum anbraten, dann herausnehmen.',
      },
      {
        step: 3,
        text: 'Zwiebel und Paprika im Bratfett drei Minuten anbraten, Paprikapulver und Reis unterrühren.',
      },
      { step: 4, text: 'Mit Brühe ablöschen, zugedeckt 18 Minuten bei kleiner Hitze garen.' },
      {
        step: 5,
        text: 'Hähnchen unterheben, zwei Minuten ziehen lassen und mit Frühlingszwiebeln bestreuen.',
      },
    ],
    createdAt: '2026-09-09T10:00:00Z',
  },
  {
    id: 10,
    slug: '10-nudelauflauf-mit-hackfleisch',
    name: 'Nudelauflauf mit Hackfleisch',
    image: null,
    description: 'Die Nudeln werden nur kurz vorgekocht und garen im Ofen fertig.',
    servings: 4,
    durationMinutes: 55,
    kcalPerServing: 600,
    proteinPerServing: 32,
    carbsPerServing: 50,
    fatPerServing: 26,
    diets: [],
    intolerances: [],
    mealTypes: ['Mittagessen', 'Abendessen'],
    equipment: ['Herd', 'Backofen'],
    attributes: ['Proteinreich', 'Meal Prep'],
    ingredients: [
      { ingredient: 'Rinderhackfleisch', amount: 500, unit: 'g' },
      { ingredient: 'Kurze Nudeln', amount: 300, unit: 'g' },
      { ingredient: 'Zwiebel', amount: 1, unit: 'Stück' },
      { ingredient: 'Passierte Tomaten', amount: 500, unit: 'g' },
      { ingredient: 'Geriebener Käse', amount: 150, unit: 'g' },
      { ingredient: 'Olivenöl', amount: 1, unit: 'EL' },
      { ingredient: 'Oregano, getrocknet', amount: 1, unit: 'TL' },
      { ingredient: 'Salz', amount: 1, unit: 'Prise' },
    ],
    cookingSteps: [
      { step: 1, text: 'Backofen auf 180 Grad Umluft vorheizen.' },
      {
        step: 2,
        text: 'Nudeln vier Minuten kürzer als auf der Packung angegeben kochen und abgießen.',
      },
      { step: 3, text: 'Zwiebel würfeln und mit dem Hackfleisch in Öl krümelig braten.' },
      {
        step: 4,
        text: 'Passierte Tomaten und Oregano dazugeben, fünf Minuten köcheln lassen und salzen.',
      },
      {
        step: 5,
        text: 'Nudeln mit der Sauce mischen, in eine Auflaufform füllen und mit Käse bestreuen.',
      },
      { step: 6, text: '25 Minuten backen, bis der Käse goldbraun ist.' },
    ],
    createdAt: '2026-09-10T10:00:00Z',
  },
  {
    id: 11,
    slug: '11-schoko-mousse-aus-avocado',
    name: 'Schoko-Mousse aus Avocado',
    image: null,
    description:
      'Reife Avocado ergibt die cremige Grundlage, im fertigen Mousse schmeckt man sie nicht heraus.',
    servings: 4,
    durationMinutes: 10,
    kcalPerServing: 190,
    proteinPerServing: 4,
    carbsPerServing: 16,
    fatPerServing: 13,
    diets: ['Vegan', 'Vegetarisch'],
    intolerances: ['Glutenfrei', 'Laktosefrei'],
    mealTypes: ['Dessert'],
    equipment: ['Mixer'],
    attributes: ['Kalorienarm', 'Wenig Zutaten'],
    ingredients: [
      { ingredient: 'Avocado, reif', amount: 2, unit: 'Stück' },
      { ingredient: 'Zartbitterschokolade, vegan', amount: 50, unit: 'g' },
      { ingredient: 'Kakaopulver', amount: 2, unit: 'EL' },
      { ingredient: 'Ahornsirup', amount: 2, unit: 'EL' },
      { ingredient: 'Salz', amount: 1, unit: 'Prise' },
    ],
    cookingSteps: [
      { step: 1, text: 'Schokolade über dem Wasserbad schmelzen und etwas abkühlen lassen.' },
      { step: 2, text: 'Avocados halbieren, entkernen und das Fruchtfleisch in den Mixer geben.' },
      { step: 3, text: 'Schokolade, Kakao, Ahornsirup und Salz dazugeben und glatt mixen.' },
      { step: 4, text: 'Auf vier Gläser verteilen und mindestens eine Stunde kalt stellen.' },
    ],
    createdAt: '2026-09-11T10:00:00Z',
  },
  {
    id: 12,
    slug: '12-ofengemuese-mit-halloumi',
    name: 'Ofengemüse mit Halloumi',
    image: null,
    description:
      'Alles kommt auf ein Blech. Der Halloumi wird erst zum Schluss dazugelegt, damit er nicht zäh wird.',
    servings: 2,
    durationMinutes: 30,
    kcalPerServing: 350,
    proteinPerServing: 20,
    carbsPerServing: 18,
    fatPerServing: 22,
    diets: ['Vegetarisch'],
    intolerances: ['Glutenfrei'],
    mealTypes: ['Mittagessen', 'Abendessen'],
    equipment: ['Backofen'],
    attributes: ['Unter 30 Min'],
    ingredients: [
      { ingredient: 'Zucchini', amount: 1, unit: 'Stück' },
      { ingredient: 'Paprika, gelb', amount: 1, unit: 'Stück' },
      { ingredient: 'Rote Zwiebel', amount: 1, unit: 'Stück' },
      { ingredient: 'Kirschtomaten', amount: 200, unit: 'g' },
      { ingredient: 'Halloumi', amount: 1, unit: 'Packung' },
      { ingredient: 'Olivenöl', amount: 2, unit: 'EL' },
      { ingredient: 'Thymian, getrocknet', amount: 1, unit: 'TL' },
    ],
    cookingSteps: [
      { step: 1, text: 'Backofen auf 220 Grad Ober- und Unterhitze vorheizen.' },
      { step: 2, text: 'Zucchini, Paprika und Zwiebel in grobe Stücke schneiden.' },
      {
        step: 3,
        text: 'Gemüse und Tomaten mit Öl und Thymian mischen und auf einem Blech verteilen.',
      },
      { step: 4, text: '15 Minuten backen, dann den Halloumi in Scheiben daraufgeben.' },
      { step: 5, text: 'Weitere zehn Minuten backen, bis der Halloumi an den Rändern Farbe hat.' },
    ],
    createdAt: '2026-09-12T10:00:00Z',
  },
]

// Picks the list fields explicitly so detail-only data never ends up in the list.
export const recipeListItems: RecipeListItem[] = recipeDetails.map((recipe) => ({
  id: recipe.id,
  slug: recipe.slug,
  name: recipe.name,
  image: recipe.image,
  durationMinutes: recipe.durationMinutes,
  kcalPerServing: recipe.kcalPerServing,
  diets: recipe.diets,
  intolerances: recipe.intolerances,
  mealTypes: recipe.mealTypes,
  equipment: recipe.equipment,
  attributes: recipe.attributes,
  createdAt: recipe.createdAt,
}))
