# Generated by Django 6.1 on 2026-08-26 23:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('proteinreich', 'Proteinreich'), ('kalorienarm', 'Kalorienarm'), ('meal-prep', 'Meal Prep'), ('unter-30-min', 'Unter 30 Min'), ('wenig-zutaten', 'Wenig Zutaten')], max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(choices=[('vegan', 'Vegan'), ('vegetarisch', 'Vegetarisch'), ('pescetarisch', 'Pescetarisch')], max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(choices=[('backofen', 'Backofen'), ('herd', 'Herd'), ('airfryer', 'Airfryer'), ('mixer', 'Mixer'), ('ohne-kochen', 'Ohne Kochen')], max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intolerance', models.CharField(choices=[('glutenfrei', 'Glutenfrei'), ('laktosefrei', 'Laktosefrei')], max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('fruehstueck', 'Frühstück'), ('mittagessen', 'Mittagessen'), ('abendessen', 'Abendessen'), ('snack', 'Snack'), ('dessert', 'Dessert')], max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='rezepte/')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('protein_per_serving', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs_per_serving', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_per_serving', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('kcal_per_serving', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('servings', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attributes', models.ManyToManyField(blank=True, to='recipes.attribute')),
                ('diets', models.ManyToManyField(blank=True, to='recipes.diet')),
                ('equipment', models.ManyToManyField(blank=True, to='recipes.equipment')),
                ('intolerances', models.ManyToManyField(blank=True, to='recipes.intolerance')),
                ('meal_types', models.ManyToManyField(blank=True, to='recipes.mealtype')),
            ],
        ),
        migrations.CreateModel(
            name='CookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('step', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.IntegerField(choices=[(10, 'g'), (11, 'kg'), (20, 'ml'), (21, 'l'), (30, 'TL'), (31, 'EL'), (32, 'Prise'), (40, 'Stück'), (41, 'Zehe'), (42, 'Bund'), (43, 'Scheibe'), (44, 'Dose'), (45, 'Packung')])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
        ),
    ]
